image: node:8.10.0
cache:
  paths:
    - node_modules/
stages:
  - setup
  - deploy
setup:
  stage: setup
  script: npm install
deploy:
  stage: deploy
  script:
    - ./node_modules/.bin/now alias --token=$NOW_TOKEN $(./node_modules/.bin/now -t $NOW_TOKEN --name=crypto-sentiment --regions=bru --npm --public -e CRYPTO_COMPARE_API_KEY=@crypto-compare-api-key -e MONGODB_URL=@mongo-db-url -e MONGODB_NAME=crypto_sentiment) crypto-sentiment; 
    - ./node_modules/.bin/now scale --token=$NOW_TOKEN crypto-sentiment.now.sh bru 1 1;
    - ./node_modules/.bin/now rm --token=$NOW_TOKEN crypto-sentiment --safe --yes
  only:
    - master