version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - mongo
    environment: 
      - MONGODB_URL=mongodb://${MONGO_NON_ROOT_USERNAME}:${MONGO_NON_ROOT_PASSWORD}@mongo:27017/crypto_sentiment
      - MONGODB_NAME=crypto_sentiment
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}         
      MONGO_INITDB_DATABASE: crypto_sentiment
      MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD} 
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
