# config.yml
version: 2
jobs:
  build:
    working_directory: ~/repo-name
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - run: npm install
      - run: sudo apt-get install jq
      - run: sudo yarn global add now now-realias now-no-alias

      - run: now -t ${NOW_TOKEN} --name=crypto-sentimeter --npm --public
      - run: now-realias
      - run: now rm -t ${NOW_TOKEN} $(now-no-alias | jq -r '.[] | .uid') -y